# Generated by Django 3.1.3 on 2021-01-16 04:46

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('is_codeexpert', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('security_question', models.CharField(blank=True, max_length=30)),
                ('security_answer', models.CharField(blank=True, max_length=30)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 46, 0, 780477), null=True)),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/')),
                ('verification_code', models.CharField(blank=True, max_length=30)),
                ('total_experience', models.FloatField(blank=True, default=None, null=True)),
                ('relevant_experience', models.FloatField(blank=True, default=None, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 46, 0, 780620), null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('sub_technology', models.ManyToManyField(blank=True, null=True, to='technology.Subtechnology')),
                ('technology', models.ManyToManyField(blank=True, null=True, to='technology.Technology')),
                ('topic', models.ManyToManyField(blank=True, null=True, to='technology.Topic')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
