# Generated by Django 3.1.3 on 2021-01-16 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 11, 38, 25, 232292), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 11, 38, 25, 232207), null=True),
        ),
    ]
