# Generated by Django 3.1.3 on 2021-01-09 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_technology',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Subtechnology'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Topic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 7, 39, 31, 625792), null=True),
        ),
    ]
