# Generated by Django 3.1.3 on 2021-01-12 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20210111_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 12, 59, 1, 669343), null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='relevant_experience',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_experience',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 12, 59, 1, 669261), null=True),
        ),
    ]
