# Generated by Django 3.1.3 on 2020-12-23 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20201223_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 11, 27, 29, 48212), null=True),
        ),
    ]
