# Generated by Django 3.1.4 on 2020-12-28 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('customuser', '0009_auto_20201228_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 28, 5, 45, 19, 470161), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_technology',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Subtechnology'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Technology'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='technology.Topic'),
        ),
    ]
