# Generated by Django 3.1.4 on 2020-12-31 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_auto_20201230_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 34, 665789), null=True),
        ),
    ]
