# Generated by Django 3.1.4 on 2021-01-02 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0014_auto_20201231_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 5, 10, 44, 754610), null=True),
        ),
    ]
