# Generated by Django 3.1.3 on 2021-01-09 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 7, 38, 54, 257704), null=True)),
                ('archived_by', models.ManyToManyField(blank=True, null=True, related_name='conversation_archived', to=settings.AUTH_USER_MODEL)),
                ('includes', models.ManyToManyField(blank=True, null=True, related_name='conversation_includes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 7, 38, 54, 259084), null=True)),
                ('message', models.CharField(max_length=1200)),
                ('is_read', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_message', to='message.conversation')),
                ('read_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
