# Generated by Django 3.1.3 on 2020-12-23 10:13

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_auto_20201223_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='archieved_by',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archived_by',
            field=models.ManyToManyField(related_name='conversation_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='includes',
            field=models.ManyToManyField(related_name='conversation_includes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 10, 13, 15, 149747), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 10, 13, 15, 151614), null=True),
        ),
    ]
