# Generated by Django 3.1.4 on 2021-01-02 10:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0014_auto_20210102_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='archived_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversation_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='includes',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversation_includes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 10, 42, 40, 126752), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 10, 42, 40, 128356), null=True),
        ),
    ]
