# Generated by Django 3.1.3 on 2021-01-09 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        ('user', '0002_auto_20210109_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 7, 40, 43, 616696), null=True)),
                ('audio', models.FileField(null=True, upload_to='videos/', verbose_name='audio')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='video')),
                ('educator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='user.educator')),
                ('topic', models.ManyToManyField(to='technology.Topic')),
            ],
        ),
    ]
