# Generated by Django 3.1.3 on 2020-12-23 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20201222_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 10, 13, 23, 317062), null=True),
        ),
    ]
