# Generated by Django 3.1.4 on 2021-01-02 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20201231_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 5, 10, 44, 760291), null=True),
        ),
    ]
