# Generated by Django 3.1.4 on 2021-01-02 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_auto_20210102_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 12, 34, 48, 873830), null=True),
        ),
    ]
