# Generated by Django 3.1.3 on 2021-01-16 04:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 42, 30, 76113), null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('MESSAGE', 'MESSAGE'), ('HIRE', 'HIRE')], max_length=100, null=True)),
                ('recieved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_notification', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_by', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 42, 30, 76669), null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_request', to='notification.request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
