# Generated by Django 3.1.3 on 2021-01-12 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20210112_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(blank=True, choices=[('MESSAGE', 'MESSAGE'), ('HIRE', 'HIRE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 16, 8, 40, 428114), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 16, 8, 40, 427518), null=True),
        ),
    ]
