# Generated by Django 3.1.3 on 2021-01-25 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20210125_1337'),
        ('notification', '0009_auto_20210124_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hire.hire'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 25, 13, 48, 8, 935062), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 25, 13, 48, 8, 934573), null=True),
        ),
    ]
