# Generated by Django 3.1.3 on 2021-02-09 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 9, 8, 1, 13, 933132), null=True)),
                ('payment_collected', models.CharField(blank=True, max_length=1200, null=True)),
            ],
        ),
    ]
