# Generated by Django 3.1.3 on 2020-12-18 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20201218_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_pending', models.BooleanField(default=False)),
                ('payment_success', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 16, 41, 49, 163122), null=True)),
                ('Educator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_client', to='user.educator')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_client', to='user.clients')),
            ],
        ),
    ]
