# Generated by Django 3.1.3 on 2021-01-09 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 9, 7, 42, 23, 281406), null=True),
        ),
    ]
