# Generated by Django 3.1.3 on 2021-01-24 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 24, 14, 32, 10, 915112), null=True),
        ),
    ]
