# Generated by Django 3.1.3 on 2020-12-18 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 16, 42, 8, 912193), null=True),
        ),
    ]
