# Generated by Django 3.1.3 on 2021-01-25 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hire', '0003_auto_20210124_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='recieved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hire',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='deadlines',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hiring_status',
            field=models.CharField(choices=[('HIRED', 'HIRED But Pending'), ('INSTRUCTOR_ACCEPTED', 'Instructor Accepted'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=19),
        ),
    ]
