# Generated by Django 3.1.3 on 2021-02-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20210125_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='hiring_status',
            field=models.CharField(choices=[('HIRED', 'HIRED But Pending'), ('INSTRUCTOR_ACCEPTED', 'Instructor Accepted'), ('INSTRUCTOR_DECLINED', 'Instructor Declined'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=19),
        ),
    ]
