# Generated by Django 3.1.3 on 2020-12-23 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_auto_20201223_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 11, 27, 29, 54657), null=True),
        ),
    ]
