# Generated by Django 3.1.4 on 2020-12-30 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_auto_20201228_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 7, 36, 40, 321463), null=True),
        ),
    ]
