# Generated by Django 3.1.3 on 2021-01-16 04:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_auto_20210116_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 41, 25, 281757), null=True)),
                ('rating', models.IntegerField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/')),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 41, 25, 281817), null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('conversation', models.ManyToManyField(blank=True, null=True, related_name='conversation_includes', to='message.Conversation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/')),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 16, 4, 41, 25, 281083), null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
