# Generated by Django 3.1.3 on 2020-11-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='secretkey',
            new_name='otp',
        ),
    ]
