# Generated by Django 3.1.3 on 2020-12-18 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 16, 41, 59, 199670), null=True),
        ),
    ]
