# Generated by Django 3.1.3 on 2020-11-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201125_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='school',
        ),
    ]
