# Generated by Django 3.1.3 on 2020-12-21 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201218_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 7, 49, 53, 92519), null=True),
        ),
    ]
