# Generated by Django 3.1.4 on 2020-12-28 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201223_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 28, 18, 52, 15, 765212), null=True),
        ),
    ]
