# Generated by Django 3.1.4 on 2020-12-30 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201228_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='educator',
            name='designation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='educator',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 7, 36, 25, 792757), null=True),
        ),
    ]
