# Generated by Django 3.1.4 on 2020-12-30 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201230_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 7, 36, 40, 318429), null=True),
        ),
    ]
