# Generated by Django 3.1.4 on 2020-12-31 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201230_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 20, 572648), null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 20, 573335), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 20, 573261), null=True),
        ),
    ]
