# Generated by Django 3.1.4 on 2020-12-31 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201231_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 34, 669341), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 34, 669833), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 48, 34, 669891), null=True),
        ),
    ]
