# Generated by Django 3.1.4 on 2021-01-02 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210102_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 9, 0, 37, 190048), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 9, 0, 37, 190508), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 9, 0, 37, 190566), null=True),
        ),
    ]
