# Generated by Django 3.1.4 on 2021-01-02 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_auto_20210102_1312'),
        ('user', '0020_auto_20210102_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='conversation',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversation_includes', to='message.Conversation'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 18, 265357), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 18, 265903), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 18, 265968), null=True),
        ),
    ]
