# Generated by Django 3.1.4 on 2021-01-02 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210102_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 39, 462284), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 39, 462754), null=True),
        ),
        migrations.AlterField(
            model_name='educator',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 13, 12, 39, 462812), null=True),
        ),
    ]
